name: Roll WebRTC revision
on:
  push:
    branches:
      - 88-sdk

jobs:
  roll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: open-webrtc-toolkit/owt-client-native
        ref: refs/heads/master
        fetch-depth: 0
        token: ${{ secrets.OWT_BOT_TOKEN }}
    - uses: actions/setup-python@v2
    - run: pip install requests
    - run: python scripts/roll_webrtc.py --base_branch master --revision $GITHUB_SHA --token $OWT_BOT_TOKEN
      env:
        OWT_BOT_TOKEN: ${{ secrets.OWT_BOT_TOKEN }}